### PR TITLE
Login backend

### PR DESCRIPTION
**Pull request by IbraCoded**

### CODE REVIEW

**Comment by IbraCoded** [comment]
Please review and approve

**Review by sirKay1010 — DISMISSED** [review]
Nicely done! Login Functionality works fine. ✔

**Comment by sirKay1010** [comment]
Merge has been approved, well-done, but please going forward, do provide description for your pull requests, so as to give background information on what the branch feature will do if merged.

**Review by palmwinecode — DISMISSED** [review]
Looks good. You can proceed to merge👍🏾

**Review by sirKay1010 — APPROVED** [review]
✔

**Pull request merged**
