### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by sirKay1010**
### Summary of changes made in this branch.
1. I added a login page to the templates folder
2. Included a basic login function to app.py
3. Included simple styling for buttons in the styles.css page
4. Removed a redundant index.html file

_Below is a picture of what the login page looks like!_
Screenshot (47)

### CODE REVIEW

**Comment by IbraCoded** [comment]
Very nice implemetation! I like the logo! However I'm wondering if the "remember me"  checkbox should be purple instead. Just a thought. Very nice though!
Screenshot (25)

**Comment by IbraCoded** [comment]
Very nice implemetation! I like the logo! However I'm wondering if the "remember me"  checkbox should be purple instead. Just a thought. Very nice though!
Screenshot (25)

**Review by IbraCoded — APPROVED** [review]

**Comment by sirKay1010** [comment]
Thank you @Mister-Sinister. Interesting thought, I will give that a try and see how it looks!

**Review by palmwinecode — APPROVED** [review]
@sirKay1010 you've done wonderful work here, this screen is beautiful! I agree with @Mister-Sinister, the purple theme should be consistent through the screen. Very well done @sirKay1010 👌🏾

**Comment by sirKay1010** [comment]
Thank you @palmwinecode, appreciate it!

**Comment by sirKay1010** [comment]
Thank you @palmwinecode, appreciate it!

**Pull request merged**
