### PR TITLE
Register backend

### PR DESCRIPTION
**Pull request by sirKay1010**
I've been able to successfully complete version 1 of the registration functionality for Beepr.

### **Sidenotes**: 
1. Please do fetch the branch and test out its validation, via both client side validation and server side validation. Will be expecting your reviews of the outcome.
2. Also incase the background color "bugs" you,😉 it can be easily commented out from the styles section within the style block at the top of the register.html page!

### CODE REVIEW

**Review by IbraCoded — COMMENTED** [review]
I see reference.txt is part of your commits

**Review by IbraCoded — COMMENTED** [review]
Hmmm. It seems the time interval while typing password is a little bit short.
Also. I think when typing in the password it should tell me my password is too weak rather than "Invalid password." I think that's a better error message

**Comment by sirKay1010** [comment]
> I see reference.txt is part of your commits

Yes it is. It's just a reference file, for often used cmds and new information for easy reference.
Do feel free to add to it or not.💯

**Comment by sirKay1010** [comment]
> 



> Hmmm. It seems the time interval while typing password is a little bit short. Also. I think when typing in the password it should tell me my password is too weak rather than "Invalid password." I think that's a better error message

- Yes, the time interval is subject to a discussion to decide what number of seconds is best user friendly to use. 
- Great observation! Will change the invalid password, to "Too weak" for the validation message.👍

**Review by IbraCoded — APPROVED** [review]
With all that being said, you may go ahead and merge

**Comment by palmwinecode** [comment]
> > I see reference.txt is part of your commits
> 
> Yes it is. It's just a reference file, for often used cmds and new information for easy reference. Do feel free to add to it or not.100

That's very thoughtful of you @sirKay1010. It will definitely come in handy👍🏾

**Review by palmwinecode — APPROVED** [review]
I agree with @Mister-Sinister that the interval should be longer but for now we can work with this. Also all validation checks were passed, you can proceed to merge. Good job @sirKay1010 !!!

**Comment by sirKay1010** [comment]
Great! Will proceed to merge immediately.
@palmwinecode and @Mister-Sinister , appreciate the observations, reviews and approvals!

**Pull request merged**
