### PR TITLE
Register

### PR DESCRIPTION
**Pull request by IbraCoded**

### CODE REVIEW

**Comment by sirKay1010** [comment]
@Mister-Sinister, Please check register template, as It doesn't render any page when run.

**Comment by IbraCoded** [comment]
Adds a register page to the app, along with a basic view for the register route

**Comment by IbraCoded** [comment]
Add a register page to Beepr, along with a basic register view.
styles.css contains styling to turn all form focus to purple

**Review by sirKay1010 — APPROVED** [review]
All changes have been reviewed. You can proceed to merge. Well done @Mister-Sinister

**Review by palmwinecode — APPROVED** [review]
Very well done @Mister-Sinister . Nice implementation of the wireframe. You can proceed to merge.

**Comment by IbraCoded** [comment]
Thank you. Merging now

**Pull request merged**
